# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/prueba-pages" # the subpath of your site, e.g. /blog/
url: "https://antorof.github.io/prueba-pages" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  antorof

# Build settings
markdown: kramdown

# or remove the 'pygments' line entirely
# pygments:         false
# highlighter:      rouge
